settings:
  application:
    enabledp: true
    host: 0.0.0.0
    mode: dev
    name: testApp
    port: 8009
    readtimeout: 1
    writertimeout: 2
  database:
    driver: mysql
    source: cootek:cootek@tcp(121.52.250.37:3306)/newu?charset=utf8&parseTime=True&loc=Local&timeout=1000ms
  gen:
    dbname: user_center
    frontpath: ../goadminui/src
  jwt:
    secret: go-admin
    timeout: 3600
  logger:
    enabledbus: true
    enableddb: false
    enabledreq: false
    level: all
    path: temp/logs
    stdout: true
